app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from . import login_manager
from flask_login import UserMixin
from datetime import datetime
# user class
class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_title = db.Column(db.String)
    pitch_content = db.Column(db.String(1000))
    category = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    comments = db.relationship('Comment',backref =  'pitch_id',lazy = "dynamic")
class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch):
        comments = Comment.query.filter_by(pitch_id=pitch).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Add New Pitch',validators = [Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    title = StringField('Title', validators = [Required()])
    text = TextAreaField('Pitch',validators = [Required()])
    category = SelectField('Category')#'),('promotion','Promotion')], validators = [Required()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    text = TextAreaField('Leave a comment:',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
# from flask_simplemde import SimpleMDE

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()
# simple=SimpleMDE()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])

    configure_uploads(app,photos)
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    # simple.init_app(app)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,url_for,abort,request,redirect
from . import main
from app import create_app
from ..models import User,Pitch,Comment
from .forms import UpdateProfile, CommentForm
from flask_login import login_required, current_user
from .. import db,photos
import datetime
# import markdown2
@main.route('/')
def index():
    title = 'Home - Welcome to Pitch App'
    return render_template('index.html')
@main.route('/pitch/', methods = ['GET','POST'])
def pitch():

    title ="PITCH- Share your pitch..."

    pitch = Pitch.get_pitch(id)
    posted_date = pitch.posted.strftime('%b %d, %Y')

    if request.args.get("like"):
        pitch.likes = pitch.likes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

    elif request.args.get("dislike"):
        pitch.dislikes = pitch.dislikes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = comment_form.text.data

        new_comment = Comment(comment = comment,user = current_user,pitch_id = pitch)

        new_comment.save_comment()


    comments = Comment.get_comments(pitch)

    return render_template("pitch/pitch.html", pitch = pitch, comment_form = comment_form, comments = comments, date = posted_date)
  
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()
    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'index.html'%}

{% block content %}
<h1>Page not found</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
{% endblock %}
<!-- Content block -->
...

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title>pitch app</title>
    {% endif %}
</head>

<body>
    <!-- Content block -->
    {% block content %}
    <div class="heading">
        <h1><strong>let's impress!</strong></h1>
        <p>"Pitch ideas on the best things to say to create a good first impression"</p>
        
    </div>


 {{macro.displayBlog(blogs)}}
   <div class="container">
           <h2 class="head">CATEGORIES</h2>
       <br>
       <br>
       <div class="thumbnail blogs">
          <a href="/pitch/pitch.html"><h3><b>Sarcastic pitches</b></h3></a>
          <br>

           <br>
       </div>
       <div class="thumbnail blogs">
         <a href=""> <h3><b>Pitches About life</b></h3></a>
          <br>
          <br>
       </div>
       <div class="thumbnail blogs">
          <a href=""><h3><b>Motivational pitches</b></h3></a>
          <br>
          <br>
       </div>
       <div class="thumbnail blogs">
         <a href=""><h3><b>Other Categories</b></h3></a>
          <br>
          <br>
           </div>
           <footer>Contact us at:<br> letsimpress@gmail.com </footer>
       </div>
<style>@import url('https://fonts.googleapis.com/css?family=Nunito');

    body{
        text-align: center;
        background-image: url("https://b.kisscc0.com/20180517/ajw/kisscc0-desktop-wallpaper-4k-resolution-high-definition-te-nature-5afd559f208de6.9913836915265519671334.jpg");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }
    footer{
        float:right;
        font-size: 20px;
    }
    h1{
        float: right;
        color: white;
        
   
    }
    heading{
        font-weight: bolder;
        color:white;
        float: right;
    }

    .head {
        color:white;
        font-family: 'Nunito', sans-serif !important;
        font-size: 40px;
        text-align: center;
        font-weight: bold;
    
    }
    .subscribe {
        font-family: 'Nunito', sans-serif !important;
    }
    
    .blogs {
        font-family: 'Nunito', sans-serif !important;
        width: 620px;
        color: black !important;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        transition: all 0.3s ease 0s;
        cursor: pointer;
        font-size: 20px;
        opacity: 0.7;
        filter: alpha(opacity=50);
    }
    
    .blogs:hover {
        box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
        transform: translateY(-7px);
    }
    p {
        font-size: 30px;
        font-weight: bolder;
    }
    
    
    .view {
        text-decoration-line: underline;
        font-family: 'Nunito', sans-serif !important;
        text-align: center;
        font-size: 20px;
        opacity: 0.9;
        filter: alpha(opacity=50);
        color:  white; 
    }
    
    .thumbnail blogs {
        text-align: center;
        font-size: 20px;
        opacity: 0.9;
        filter: alpha(opacity=50);
        color:  white; 
    
    }
    a{
        color: black
    }
    </style>
               
</body>
{% endblock %}

app/templates/macros.html
<!--display blog in macros-->
{% macro displayBlog(blog_list) %}
    {% for blog in blog_list %}
        <h3 class="title"><a href="/blog/{{blog.id}}">{{blog.title}}</a></h3>
        <p class="posted">Posted on: <b>{{blog.posted}}</b></p>
        <hr>
    {% endfor %}
    <style>
            @import url('https://fonts.googleapis.com/css?family=Nunito');
           .title{
               font-family: 'Nunito', sans-serif !important; 
           }
           .posted{
               font-family: 'Nunito', sans-serif !important;
           }
       </style>
{% endmacro %}

{% macro displayComments(comment_list) %}
{% for comment in comment_list %}
<div class="row col-lg-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="writerr">Blog Writer: <i>{{ comment.name }}</i></p> 
        </div>
        <div class="panel-body">
            <p class="comment">{{ comment.comment_itself}}</p>
        </div>
        <div class="panel-footer">
            <i class="posted">{{comment.posted}}</i>
        </div>
    </div>
</div>         
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
         <li><a class="navbar-brand" > <a href="/" class="btn btn-md buttons">
          <span class="glyphicon glyphicon-home"></span> Home
        </a></a></li>                        
         <ul class="nav navbar-nav navbar-right">
             {% if current_user.is_authenticated %}
             <li><a href="{{url_for('main.profile',uname=current_user.username)}}" class="user"style="color:white; font-weight:bolder;"><span class="glyphicon glyphicon-user"></span> &nbsp;{{current_user.username}}</a></li>
             <li><a href="{{url_for('auth.logout')}}" class="user"style="color:white; font-weight:bolder;" class="logout"><span class="glyphicon glyphicon-log-out"></span>&nbsp;Log out</a></li>
             {% else %}
             <li><a href="{{url_for('auth.login')}}" class="login"><span class="glyphicon glyphicon-log-in"></span>&nbsp;Log in</a></li>
             {% endif %}
         </ul>
            </ul>
        </div>

    </div>
<style>
    a{
        box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
        transform: translateY(-7px);
        opacity: 0.9;
        filter: alpha(opacity=50);
        color:  white; 
        font-weight: bolder;
    }
</style>
</div>

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="row" style="margin-top: 50px">
  <div class="col-md-3"> </div>
  <div class="col-md-6" style="border: 1px solid #372e5f; padding: 30px 10px; border-radius: 5px; font-size: 16px;">
    <h2 class="text-center" style="border-bottom: 2px solid #372e5f; color: #372e5f; padding-bottom: 10px;">New Pitch</h2>
    {{ wtf.quick_form(pitch_form) }}
  </div>
  <div clas="col-md-3"> </div>
</div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
{{ super() }}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{%endblock%}
<!-- Content block -->
{%block content%}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="row">
        <h4>{{pitch.pitch_title}}</h4>
        <p>{{pitch.pitch_content}}</p>
        <small>Posted on {{date}} by {{pitch.user.username}}</small>
        <div class="row">
          <div class="col-md-3">
            <a href="/pitch/{{pitch.id}}?like=1">
              <i class="fas fa-thumbs-up" style="color: #372e5f; font-size: 24px;"></i>
            </a><span style="font-size: 16px;">{{pitch.likes}}</span>
          </div>
          <div class="col-md-3"></div>
          <div class="col-md-3"></div>
          <div class="col-md-3">
            <a href="/pitch/{{pitch.id}}?dislike=1">
              <i class="fas fa-thumbs-down" style="color: #060216; font-size: 24px;"></i>
            </a><span style="font-size: 16px;">{{pitch.dislikes}}</span>
          </div>
        </div>
      </div>
      <div class="row">
        <h3 class="text-center" style="border-bottom: 1px solid #372e5f; padding-bottom: 10px;">Comments</h3>
        {% if current_user.is_authenticated %}
        <h3 class="text-center" style="border-bottom: 2px solid #372e5f; color: #372e5f; padding-bottom: 10px;">New Comment</h3>
        {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>

</div>
{%endblock%}

app/templates/pitch/pitch.html
{% extends 'base.html'%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='index.css')}}">
{% endblock %}
{% block content %}
<div class="container">
    <h1 style="text-align:center">Share your Pitch...</h1>
    <div class="row1">
        <h1>Media Pitch</h1>
        <p>Always target the right beat</p>
        <p>Posted on {{date}} by {{pitch.user.username| capitalize}}</p>
        <a href="/pitch/{{pitch.id}}?like=1" class="col btn btn-success">Like
        </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">Dislike</a>
        <p>Target specific writers, not publications</p>
        <p class="col">{{numberOfLikes}}</p>
        <button class="col btn btn-success" (click)="likeButtonClick()">Like</button>
        <button class="col btn btn-danger" (click)="dislikeButtonClick()">Dislike</button>
        <h4>Comments</h4>
        <hr>
        {% if current_user.is_authenticated %}
        {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
    </div>
    <div class="row2">
        <h1>Job promotion Pitch</h1>
        <p>Negotiate a Lateral Move Salary</p>
        <p class="col">{{numberOfLikes}}</p>
        <a href="/pitch/{{pitch.id}}?like=1" class="col btn btn-success">Like
        </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">Dislike</a>
        <p>Write a Letter to a Company Requesting Job Responsibilities</p>
        <p class="col">{{numberOfLikes}}</p>
        <a href="/pitch/{{pitch.id}}?like=1" class="col btn btn-success">Like
        </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">Dislike</a>
        <h4>Comments</h4>
        <hr>
        {% if current_user.is_authenticated %}
        {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
    </div>
    </div>
</div>
<style>
    body{
        text-align: center;
        background-image: url("https://b.kisscc0.com/20180517/ajw/kisscc0-desktop-wallpaper-4k-resolution-high-definition-te-nature-5afd559f208de6.9913836915265519671334.jpg");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }
    </style>
    <footer>
        <a href="{{url_for('main.pitch',category=sarcastic)}}"><h3><b>Sarcastic pitches</b></h3></a>

        <a href="{{url_for('main.pitch',category=life)}}"> <h3><b>Pitches About life</b></h3></a>

        <a href="{{url_for('main.pitch',category=motivation)}}"><h3><b>Motivational pitches</b></h3></a>

        <a href="{{url_for('main.pitch',category=other)}}"><h3><b>Other Categories</b></h3></a>

    </footer>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<body>
<div class="container">
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>    
    <div class="row">
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

            {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
            
                <input type="file" name="photo" class="form-control">
                <input type="submit">
        </form>
        <br>
        <br>
        <a href="{{url_for('main.update_profile',uname=user.username)}}" style="border-width: 2px;
border-style: solid; margin-left:500px">Add New Pitch</a><br>
            {% endif %}
        </div>
     </div>

    
</body>

<style>
    body{
        text-align: center;
        background-image: url("https://b.kisscc0.com/20180517/ajw/kisscc0-desktop-wallpaper-4k-resolution-high-definition-te-nature-5afd559f208de6.9913836915265519671334.jpg");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        color: white;
    }
    a{
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        transition: all 0.3s ease 0s;
        cursor: pointer;
        font-size: 20px;
        opacity: 0.7;
        filter: alpha(opacity=50);
        color: aliceblue;
    }

</style>
    {% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}